const data = {
  event_type:'boda',
  nombre_novia:'Kaire Mariam',
  nombre_novio:'Juan Carlos',
  nombre_papa_novia:'',
  nombre_mama_novia:'',
  nombre_papa_novio:'',
  nombre_mama_novio:'',
  frase:'El amor nos ha llevado a vivir este momento mágico y especial de nuestras vidas. Te invitamos a ser testigo de nuestra promesa de amor',
  img_header:'back.webp',
  img_fondo1:'',
  img_fondo2:'',
  fecha_dia:'23',
  fecha_mes:'Noviembre',
  fecha_year:'2024',
  religiosa_hora:'17',
  religiosa_minutos:'00',
  religiosa_lugar:'Parroquia de San Gerardo María Mayela',
  religiosa_direccion:'Abasolo 56',
  religiosa_direccion_col:'Centro',
  religiosa_direccion_cd:'Iguala de la Independencia.',
  religiosa_ubicacion:'https://maps.app.goo.gl/HmPdng5RgSRjZoFLA',
  recepcion_hora:'18',
  recepcion_minutos:'00',
  recepcion_lugar:'Salón de Eventos Mahogani',
  recepcion_direccion:'Industria de la transformación 4',
  recepcion_direccion_col:'Ciudad Industrial',
  recepcion_direccion_cd:'Iguala de la Independencia.',
  recepcion_ubicacion:'https://maps.app.goo.gl/erq3LJEaxZQDhqoZ8',
  confirmacion_novia:'2204633145',
  confirmacion_novio:'',
  regalos_frase:'',
  regalos_url:'https://mesaderegalos.liverpool.com.mx/milistaderegalos/51513332'
}

export default data